version: '3'

services:
  postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=1111'
      - 'POSTGRES_DB=dudeWhereIsMyCar'
      - 'POSTGRES_HOST=postgres'
    expose:
      - 5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: toha@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1111

  app:
    build: ./
    container_name: 'DudeWhereIsMyCar_backend'
    ports:
      - "8080:8080"
    depends_on:
      - postgres



