#http://localhost:8080/api/swagger-ui.html
#http://localhost:8080/api/v3/api-docs
#http://localhost:5050/browser/
#http://localhost:5601/app/home#/

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://car_app_postgres:5432/dudeWhereIsMyCar
    password: '1111'
  web:
    locale: en_US
  security:
    user:
      name: user
      password: '1111'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'

  kafka:
    producer:
      bootstrap-servers: broker:29092
    consumer:
      bootstrap-servers: broker:29092


server:
  servlet:
    contextPath: /api
logging:
  level:
    org:
      springframework:
        web: TRACE
