#http://localhost:8080/api/swagger-ui.html
#http://localhost:8080/api/v3/api-docs
#http://localhost:5050/browser/
#http://localhost:5601/app/home#/



spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://car_app_postgres:5432/dudeWhereIsMyCar
    password: '1111'
  web:
    locale: en_US
  security:
    user:
      name: user
      password: '1111'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'

  kafka:
    producer:
      bootstrap-servers: broker:29092
    consumer:
      bootstrap-servers: broker:29092
schedulerPrint:
  intervalMs: 30000
  initialDelayMs: 0

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

  prometheus:
    metrics:
      export:
        enabled: true
#keytool -genkeypair -alias DudeWhereIsMyCar -keyalg RSA -keysize 4096 -storetype PKCS12 -keystore keystore.p12 -validity 3650 -storepass Qwerty123
server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: Qwerty123
    key-store-type: pkcs12
    key-alias: DudeWhereIsMyCar
    key-password: Qwerty123

  servlet:
    contextPath: /api
logging:
  level:
    org:
      springframework:
        web: TRACE

