app:
  name: 'Dude Where Is MyCar'
  version: '1.01'



spring:
  datasource:
    username: ${DATASOURCE_USERNAME}
    url: ${DATASOURCE_URL}
    password: ${DATASOURCE_PASSWORD}
  web:
    locale: en_US
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'

  feign:
    config:
      name: ${FEIGN_CONFIG_NAME}
      url: ${FEIGN_CONFIG_URL}
      value:
        get_rate: ${FEIGN_CONFIG_VALUE_GET_RATE}





  kafka:
    producer:
      bootstrap-servers: broker:29092
    consumer:
      bootstrap-servers: broker:29092





schedulerPrint:
  intervalMs: 30000
  initialDelayMs: 0

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

  prometheus:
    metrics:
      export:
        enabled: true
#keytool -genkeypair -alias dude_where_is_my_car -keyalg RSA -keysize 4096 -storetype PKCS12 -keystore keystore.p12 -validity 3650 -storepass Qwerty123
server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: Qwerty123
    key-store-type: pkcs12
    key-alias: DudeWhereIsMyCar
    key-password: Qwerty123

  servlet:
    contextPath: /api
logging:
  level:
    org:
      springframework:
        web: TRACE

