version: '3.9'
services:

  currencies:
    build: ./
    container_name: 'currencies'
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    networks:
      - currenciesDb
      - currencies


  postgres:
    image: postgres:15
    container_name: currencies_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: currencies
      POSTGRES_HOST: postgres
    expose:
      - 5432
    ports:
      - "5433:5432"
    networks:
      - currenciesDb




  pgadmin:
    image: dpage/pgadmin4
    container_name: currencies_pgadmin4_container
    restart: always
    ports:
      - "5051:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: toha@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1111
    networks:
      - currenciesDb

networks:
  currenciesDb:
    driver: bridge
  currencies:
    name: shared-currencies
    driver: bridge



